### PR TITLE
[BUG] A11y - Landmarks should have a unique role or role/label/title (i.e. accessible name) combination

### LINKED ISSUE #36: [BUG] A11y - Landmarks should have a unique role or role/label/title (i.e. accessible name) combination
### Description

When running the a11y test
```
npx playwright test
```
following error occurs
```
Object {
+     "description": "Landmarks should have a unique role or role/label/title (i.e. accessible name) combination",
+     "help": "Ensures landmarks are unique",
+     "helpUrl": "https://dequeuniversity.com/rules/axe/4.8/landmark-unique?application=playwright",
+     "id": "landmark-unique",
+     "impact": "moderate",
+     "nodes": Array [
+       Object {
+         "all": Array [],
+         "any": Array [
+           Object {
+             "data": Object {
+               "accessibleText": null,
+               "role": "navigation",
+             },
+             "id": "landmark-is-unique",
+             "impact": "moderate",
+             "message": "The landmark must have a unique aria-label, aria-labelledby, or title to make landmarks distinguishable",
+             "relatedNodes": Array [
+               Object {
+                 "html": "<div role=\"navigation\">",
+                 "target": Array [
+                   "div[role=\"navigation\"]",
+                 ],
+               },
+             ],
+           },
+         ],
+         "failureSummary": "Fix any of the following:
+   The landmark must have a unique aria-label, aria-labelledby, or title to make landmarks distinguishable",
+         "html": "<nav><ul><li><a href=\"#\">Home</a></li><li><a href=\"#\">Courses</a></li></ul></nav>",
+         "impact": "moderate",
+         "none": Array [],
+         "target": Array [
+           "nav",
+         ],
+       },
+     ],
+     "tags": Array [
+       "cat.semantics",
+       "best-practice",
+     ],
+   },
```

### Acceptance requirement

- [ ] update landmarks to dismiss the error

### PR DESCRIPTION
**Pull request by Chizycodes**
## Description

This PR fixes the playwright bug "Landmarks should have a unique role or role/label/title (i.e. accessible name) combination".

## Fixes Issue

Closes #36 

## Acceptance Criteria

- [x] update landmarks to dismiss the error.

## Type of Changes

:bug: Bug fix

### Before

```
Object {
+     "description": "Landmarks should have a unique role or role/label/title (i.e. accessible name) combination",
+     "help": "Ensures landmarks are unique",
+     "helpUrl": "https://dequeuniversity.com/rules/axe/4.8/landmark-unique?application=playwright",
+     "id": "landmark-unique",
+     "impact": "moderate",
+     "nodes": Array [
+       Object {
+         "all": Array [],
+         "any": Array [
+           Object {
+             "data": Object {
+               "accessibleText": null,
+               "role": "navigation",
+             },
+             "id": "landmark-is-unique",
+             "impact": "moderate",
+             "message": "The landmark must have a unique aria-label, aria-labelledby, or title to make landmarks distinguishable",
+             "relatedNodes": Array [
+               Object {
+                 "html": "<div role=\"navigation\">",
+                 "target": Array [
+                   "div[role=\"navigation\"]",
+                 ],
+               },
+             ],
+           },
+         ],
+         "failureSummary": "Fix any of the following:
+   The landmark must have a unique aria-label, aria-labelledby, or title to make landmarks distinguishable",
+         "html": "<nav><ul><li><a href=\"#\">Home</a></li><li><a href=\"#\">Courses</a></li></ul></nav>",
+         "impact": "moderate",
+         "none": Array [],
+         "target": Array [
+           "nav",
+         ],
+       },
+     ],
+     "tags": Array [
+       "cat.semantics",
+       "best-practice",
+     ],
+   },
```

### After

Screenshot from 2023-10-15 14-34-08

## Testing Steps / QA Criteria

```
npm run test:a11y
```

### CODE REVIEW

File: components/content/TableOfContents.jsx [hunk 1]
```diff
@@ -5,7 +5,7 @@ import { FaTimes } from "react-icons/fa";
 
 const TableOfContents = ({ toggleMenu }) => {
   return (
-    <div role="navigation">
```
Comment (YuriDevAT) [inline components/content/TableOfContents.jsx:8]: I would suggest rather than deleting the role, change the `<div>` to a `<nav>`. A table of content is kind of a navigation, this information is useful for screen reader users. If the accessibility test still fails, add an aria-label with table of contents or such, to make the `<nav>` unique. This should do the trick. If not, please reach out to me 😄

**Review by YuriDevAT — CHANGES_REQUESTED** [review]
Please check out the source code of the table of content from MDN https://developer.mozilla.org/en-US/docs/Learn/HTML/Tables/Advanced I actually like how they put it into an `<aside>` tag. I guess it would make sense to use it this way. Would you agree? Or have another suggestion? Please let me know.

**Comment by YuriDevAT** [comment]
I really like your PRs. They are detailed and concise. It makes my maintainer experience pleasant and I am grateful for that 😌

**Review by YuriDevAT — APPROVED** [review]
Very well done, @Chizycodes. Thank you for your contribution 🥳
